In [1]:
import sqlite3
import pandas as pd

In [2]:
conn=sqlite3.connect("fraud_analysis.db")
cursor=conn.cursor()

In [7]:
import os
os.listdir()

['.anaconda',
 '.conda',
 '.continuum',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.matplotlib',
 '.ms-ad',
 '.python_history',
 '.vscode',
 '3D Objects',
 'anaconda3',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'Desktop',
 'Documents',
 'Downloads',
 'employees.csv',
 'Favorites',
 'fraud_analysis.db',
 'high_salary',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'Microsoft',
 'Music',
 'My Documents',
 'NetHood',
 'notes.txt',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{3abdd868-d2af-11f0-a864-f975102cbd03}.TM.blf',
 'NTUSER.DAT{3abdd868-d2af-11f0-a864-f975102cbd03}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{3abdd868-d2af-11f0-a864-f975102cbd03}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'Pictures',
 'PrintHood',
 'project1.py',
 'PyCharmMiscProject',
 'PycharmProjects',
 'Recent',
 'result.txt',
 'salary_report.txt',
 'Saved Games',
 'Searches',
 'SendTo',
 'sql_notebook',
 'Start Menu',
 'Templates',
 'Untitled.ipynb',
 'Videos']

In [8]:
import os
os.listdir()

['.anaconda',
 '.conda',
 '.continuum',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.matplotlib',
 '.ms-ad',
 '.python_history',
 '.vscode',
 '3D Objects',
 'anaconda3',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'Desktop',
 'Documents',
 'Downloads',
 'employees.csv',
 'Favorites',
 'fraud_analysis.db',
 'high_salary',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'Microsoft',
 'Music',
 'My Documents',
 'NetHood',
 'notes.txt',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{3abdd868-d2af-11f0-a864-f975102cbd03}.TM.blf',
 'NTUSER.DAT{3abdd868-d2af-11f0-a864-f975102cbd03}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{3abdd868-d2af-11f0-a864-f975102cbd03}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'Pictures',
 'PrintHood',
 'project1.py',
 'PyCharmMiscProject',
 'PycharmProjects',
 'Recent',
 'result.txt',
 'salary_report.txt',
 'Saved Games',
 'Searches',
 'SendTo',
 'sql_notebook',
 'Start Menu',
 'Templates',
 'Untitled.ipynb',
 'Videos']

In [11]:
df=pd.read_csv("c:/users/DELL/Desktop/bank_fraud_sql_analysis/fraud_data.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'c:/users/DELL/Desktop/bank_fraud_sql_analysis/fraud_data.csv'

In [13]:
df=pd.read_csv(r"C:\Users\DELL-R7\Desktop\bank_fraud_sql_analysis\fraud_data.csv")
df.head()

C:\Users\DELL-R7\AppData\Local\Temp\ipykernel_13276\1643523637.py:1: DtypeWarning: Columns (1,3,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(r"C:\Users\DELL-R7\Desktop\bank_fraud_sql_analysis\fraud_data.csv")

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1.0,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0.0,0.0
1,1.0,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0.0,0.0
2,1.0,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1.0,0.0
3,1.0,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1.0,0.0
4,1.0,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0.0,0.0

In [14]:
df.to_sql("fraud_transactions",conn,if_exists="replace",index=False)

999637

In [15]:
pd.read_sql_query("select count(*)from fraud_transactions",conn)

   count(*)
0    999637

In [16]:
pd.read_sql_query("""
select type, count(*) as totaltransactions
from fraud_transactions
group by type
""",conn)

       type  totaltransactions
0      None             899638
1   CASH_IN              20185
2  CASH_OUT              30718
3     DEBIT                988
4   PAYMENT              39511
5  TRANSFER               8597

In [17]:
pd.read_sql_query("""
SELECT isFraud, COUNT(*) as count
FROM fraud_transactions
GROUP BY isFraud
""", conn)

   isFraud   count
0      NaN  899638
1      0.0   99883
2      1.0     116

In [18]:
pd.read_sql_query("""
SELECT SUM(amount) as total_fraud_amount
FROM fraud_transactions
WHERE isFraud = 1
""", conn)

   total_fraud_amount
0          62823097.2

In [19]:
pd.read_sql_query("""
SELECT type, COUNT(*) AS fraud_count
FROM fraud_transactions
WHERE isFraud = 1
GROUP BY type
ORDER BY fraud_count DESC
""", conn)

       type  fraud_count
0  CASH_OUT           59
1  TRANSFER           57

In [20]:
pd.read_sql_query("""
SELECT nameOrig, nameDest, amount
FROM fraud_transactions
WHERE isFraud = 1
ORDER BY amount DESC
LIMIT 10
""", conn)

      nameOrig     nameDest       amount
0     C7162498   C945327594  10000000.00
1   C351297720   C766681183  10000000.00
2   C666654362  C1726301214   5460002.91
3  C1588880909  C1570256460   5460002.91
4  C2047521920   C449261773   2930418.44
5  C2044690596   C932583850   2930418.44
6   C394488466   C575638324   2539898.07
7   C728718059  C1013511446   2539898.07
8  C1334405552   C431687661   1277212.77
9   C467632528   C716083600   1277212.77

In [21]:
pd.read_sql_query("""
SELECT AVG(amount) AS avg_fraud_amount
FROM fraud_transactions
WHERE isFraud = 1
""", conn)

   avg_fraud_amount
0     541578.424138

In [22]:
pd.read_sql_query("""
SELECT 
ROUND(
SUM(CASE WHEN isFraud=1 THEN 1 ELSE 0 END)*100.0/COUNT(*),2
) AS fraud_percentage
FROM fraud_transactions
""", conn)

   fraud_percentage
0              0.01

In [23]:
pd.read_sql_query("""
SELECT type, COUNT(*) AS fraud_count
FROM fraud_transactions
WHERE isFraud = 1
GROUP BY type
ORDER BY fraud_count DESC
""", conn)

       type  fraud_count
0  CASH_OUT           59
1  TRANSFER           57

In [24]:
pd.read_sql_query("""
SELECT nameOrig, COUNT(*) AS fraud_count
FROM fraud_transactions
WHERE isFraud = 1
GROUP BY nameOrig
ORDER BY fraud_count DESC
LIMIT 10
""", conn)

     nameOrig  fraud_count
0  C921533797            1
1  C903383636            1
2  C864622150            1
3  C858959216            1
4  C840095827            1
5  C840083671            1
6  C788790720            1
7  C786114805            1
8  C777407608            1
9   C77163673            1

In [25]:
pd.read_sql_query("""
SELECT nameOrig, nameDest, amount
FROM fraud_transactions
WHERE isFraud = 1
ORDER BY amount DESC
LIMIT 10
""", conn)

      nameOrig     nameDest       amount
0     C7162498   C945327594  10000000.00
1   C351297720   C766681183  10000000.00
2   C666654362  C1726301214   5460002.91
3  C1588880909  C1570256460   5460002.91
4  C2047521920   C449261773   2930418.44
5  C2044690596   C932583850   2930418.44
6   C394488466   C575638324   2539898.07
7   C728718059  C1013511446   2539898.07
8  C1334405552   C431687661   1277212.77
9   C467632528   C716083600   1277212.77